// Command casefold generates parser/casefold_gen.go from the checked-in
// Unicode CaseFolding.txt snapshot. Generation is deliberately offline;
// updating the Unicode version and checksum is a separate reviewable act.
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"
)

const (
	defaultSource  = "internal/generate/casefold/CaseFolding-15.0.0.txt"
	sourceURL      = "https://www.unicode.org/Public/15.0.0/ucd/CaseFolding.txt"
	unicodeVersion = "15.0.0"
	sourceSHA      = "cdd49e55eae3bbf1f0a3f6580c974a0263cb86a6a08daa10fbf705b4808a56f7"
	wantEntries    = 1530
	wantRunes      = 1650
)

type caseFold struct {
	source rune
	target []rune
}

func main() {
	source := flag.String("source", defaultSource, "checked-in Unicode CaseFolding.txt")
	out := flag.String("out", "parser/casefold_gen.go", "generated Go file")
	flag.Parse()

	data, err := os.ReadFile(*source)
	if err != nil {
		fatal(err)
	}
	if got := fmt.Sprintf("%x", sha256.Sum256(data)); got != sourceSHA {
		fatal(fmt.Errorf("source SHA-256 = %s, want %s", got, sourceSHA))
	}
	folds, err := parse(data)
	if err != nil {
		fatal(err)
	}
	generated, err := render(folds)
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*out, generated, 0o644); err != nil {
		fatal(err)
	}
}

func parse(data []byte) ([]caseFold, error) {
	scanner := bufio.NewScanner(bytes.NewReader(data))
	folds := make([]caseFold, 0, wantEntries)
	seen := make(map[rune]struct{}, wantEntries)
	lineNumber := 0
	for scanner.Scan() {
		lineNumber++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Split(line, ";")
		if len(fields) < 3 {
			return nil, fmt.Errorf("line %d: malformed record", lineNumber)
		}
		status := strings.TrimSpace(fields[1])
		if status != "C" && status != "F" {
			continue
		}
		source, err := parseRune(strings.TrimSpace(fields[0]))
		if err != nil {
			return nil, fmt.Errorf("line %d source: %w", lineNumber, err)
		}
		if _, ok := seen[source]; ok {
			return nil, fmt.Errorf("line %d: duplicate default full mapping for U+%04X", lineNumber, source)
		}
		seen[source] = struct{}{}

		spellings := strings.Fields(fields[2])
		if len(spellings) == 0 {
			return nil, fmt.Errorf("line %d: empty mapping", lineNumber)
		}
		target := make([]rune, len(spellings))
		for i, spelling := range spellings {
			target[i], err = parseRune(spelling)
			if err != nil {
				return nil, fmt.Errorf("line %d mapping: %w", lineNumber, err)
			}
		}
		folds = append(folds, caseFold{source: source, target: target})
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan CaseFolding.txt: %w", err)
	}
	sort.Slice(folds, func(i, j int) bool { return folds[i].source < folds[j].source })
	if len(folds) != wantEntries {
		return nil, fmt.Errorf("parsed %d C/F mappings, want %d", len(folds), wantEntries)
	}
	runes := 0
	for _, fold := range folds {
		runes += len(fold.target)
	}
	if runes != wantRunes {
		return nil, fmt.Errorf("parsed %d mapped runes, want %d", runes, wantRunes)
	}
	return folds, nil
}

func parseRune(spelling string) (rune, error) {
	codepoint, err := strconv.ParseUint(spelling, 16, 32)
	if err != nil {
		return 0, fmt.Errorf("parse %q: %w", spelling, err)
	}
	r := rune(codepoint)
	if !utf8.ValidRune(r) {
		return 0, fmt.Errorf("%q is not a Unicode scalar value", spelling)
	}
	return r, nil
}

func render(folds []caseFold) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintf(&out, `// Code generated by internal/generate/casefold; DO NOT EDIT.
//
// Data source: Unicode %s CaseFolding.txt
// %s
// SHA-256: %s
//
// Only the C and F records are included: Unicode's default full case fold.
// The locale-specific T records and simple-only S records are excluded.

package parser

type fullCaseFoldEntry struct {
	source rune
	offset uint16
	length uint8
}

var fullCaseFoldEntries = [...]fullCaseFoldEntry{
`, unicodeVersion, sourceURL, sourceSHA)
	offset := 0
	for _, fold := range folds {
		fmt.Fprintf(&out, "\t{0x%04X, %d, %d},\n", fold.source, offset, len(fold.target))
		offset += len(fold.target)
	}
	out.WriteString("}\n\nvar fullCaseFoldRunes = [...]rune{\n")
	for _, fold := range folds {
		out.WriteByte('\t')
		for _, r := range fold.target {
			fmt.Fprintf(&out, "0x%04X, ", r)
		}
		out.WriteByte('\n')
	}
	out.WriteString("}\n")
	return format.Source(out.Bytes())
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
