// Command entities generates parser/entities_gen.go from the checked-in
// WHATWG named character reference snapshot. Generation is deliberately
// offline; updating the snapshot and its checksum is a separate reviewable act.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
)

const (
	defaultSource = "internal/generate/entities/entities.json"
	sourceURL     = "https://html.spec.whatwg.org/entities.json"
	retrieved     = "2026-08-08"
	sourceSHA     = "d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6"
)

type entity struct {
	name  string
	value string
}

type sourceEntity struct {
	Codepoints []uint32 `json:"codepoints"`
	Characters string   `json:"characters"`
}

func main() {
	source := flag.String("source", defaultSource, "checked-in WHATWG entities.json")
	out := flag.String("out", "parser/entities_gen.go", "generated Go file")
	flag.Parse()

	data, err := os.ReadFile(*source)
	if err != nil {
		fatal(err)
	}
	if got := fmt.Sprintf("%x", sha256.Sum256(data)); got != sourceSHA {
		fatal(fmt.Errorf("source SHA-256 = %s, want %s", got, sourceSHA))
	}
	entities, err := parse(data)
	if err != nil {
		fatal(err)
	}
	generated, err := render(entities)
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*out, generated, 0o644); err != nil {
		fatal(err)
	}
}

func parse(data []byte) ([]entity, error) {
	var source map[string]sourceEntity
	if err := json.Unmarshal(data, &source); err != nil {
		return nil, fmt.Errorf("parse WHATWG entities.json: %w", err)
	}

	entities := make([]entity, 0, 2125)
	for spelling, sourceEntity := range source {
		// WHATWG also lists 106 legacy spellings that HTML accepts without a
		// semicolon. CommonMark deliberately accepts only the strict form.
		if !strings.HasPrefix(spelling, "&") || !strings.HasSuffix(spelling, ";") {
			continue
		}
		runes := make([]rune, len(sourceEntity.Codepoints))
		for i, codepoint := range sourceEntity.Codepoints {
			runes[i] = rune(codepoint)
		}
		if got := string(runes); got != sourceEntity.Characters {
			return nil, fmt.Errorf("%s characters %q disagree with codepoints %q", spelling, sourceEntity.Characters, got)
		}
		entities = append(entities, entity{
			name:  spelling[1 : len(spelling)-1],
			value: sourceEntity.Characters,
		})
	}
	if len(entities) != 2125 {
		return nil, fmt.Errorf("parsed %d semicolon-terminated entities, want 2125", len(entities))
	}
	sort.Slice(entities, func(i, j int) bool { return entities[i].name < entities[j].name })
	return entities, nil
}

func render(entities []entity) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintf(&out, `// Code generated by internal/generate/entities; DO NOT EDIT.
//
// Data source: WHATWG HTML Living Standard named character references
// %s
// Retrieved: %s
// SHA-256: %s
//
// This table contains only the 2125 semicolon-terminated names accepted by
// CommonMark; WHATWG's legacy semicolon-free aliases are intentionally omitted.

package parser

var htmlEntities = [...]htmlEntity{
`, sourceURL, retrieved, sourceSHA)
	for _, entity := range entities {
		fmt.Fprintf(&out, "\t{%s, %s},\n", strconv.Quote(entity.name), strconv.QuoteToASCII(entity.value))
	}
	out.WriteString("}\n")
	return format.Source(out.Bytes())
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
